"""Modify schema; Add medication,dosage and user_id collumns in Treatment

Revision ID: 30098fc343ae
Revises: 70a6f835a9f8
Create Date: 2025-10-02 13:16:16.704773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30098fc343ae'
down_revision = '70a6f835a9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medication', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dosage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('dosage')
        batch_op.drop_column('medication')

    # ### end Alembic commands ###
