"""Add more fields to Sale model

Revision ID: 3933a395e8bf
Revises: f52a6cb00c68
Create Date: 2025-10-05 22:17:04.585939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3933a395e8bf'
down_revision = 'f52a6cb00c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_received', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sale_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['animal_id'])
        batch_op.create_unique_constraint(None, ['receipt_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('sale_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('purpose')
        batch_op.drop_column('receipt_number')
        batch_op.drop_column('payment_received')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('buyer_contact')

    # ### end Alembic commands ###
