"""Migrate Breeding model

Revision ID: 80450ccbc047
Revises: 60ae99862875
Create Date: 2025-10-11 22:14:23.179694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80450ccbc047'
down_revision = '60ae99862875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeding_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mating_date', sa.Date(), nullable=False),
    sa.Column('expected_kidding_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('doe_id', sa.Integer(), nullable=False),
    sa.Column('buck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buck_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['doe_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breeding_records')
    # ### end Alembic commands ###
