"""Modify schema; Add acqusition details and ssource to Animal,add outcome and cost in Transaction,add profy column in Sale

Revision ID: 82a4e4b96474
Revises: 3933a395e8bf
Create Date: 2025-10-06 16:39:10.780891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a4e4b96474'
down_revision = '3933a395e8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquisition_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('acquisition_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('offspring_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit', sa.Float(), nullable=True))

    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('outcome')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('profit')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('offspring_count')
        batch_op.drop_column('source')
        batch_op.drop_column('acquisition_price')
        batch_op.drop_column('acquisition_date')

    # ### end Alembic commands ###
