"""Add category,image_url,created_at, updated_at,mother_id and father_id columns to the Animal table

Revision ID: ce27dae9180c
Revises: 
Create Date: 2025-10-01 10:51:39.872232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce27dae9180c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mother_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('father_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'animals', ['mother_id'], ['id'])
        batch_op.create_foreign_key(None, 'animals', ['father_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('father_id')
        batch_op.drop_column('mother_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('image_url')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
