"""Comment user_id temporarily in Treatement

Revision ID: f52a6cb00c68
Revises: 30098fc343ae
Create Date: 2025-10-02 14:08:35.521433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52a6cb00c68'
down_revision = '30098fc343ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('treatments_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('treatments_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
